- ualrdm-directory-validation/directory-validate.py
- ualrdm-directory-validation/ualrdm-curationdirectory-schema.json
Change the json schema to allow more flexibility in the curation packages. Allows more missing files that aren't relevant for preservation, more flexibility in naming of required files
Fixes #8 
Run [directory-validate.py](https://github.com/UAL-RE/ReBACH/blob/main/ualrdm-directory-validation/directory-validate.py) on the testing data with the [ualrdm-curationdirectory-schema.json](https://github.com/UAL-RE/ReBACH/blob/main/ualrdm-directory-validation/ualrdm-curationdirectory-schema.json) schema
> Bug: make curation validation less strict

- .gitignore
- bagger/README.md
Fixes some typos and adds documentation of Bagger.Status return values.
> README updates

- bagger/bag.py
- figshare/Article.py
- figshare/Integration.py
This pull request contains code that fixes the bug #36 
1. The variable 'version' holds the value 'v01'. Therefore, adding 'v' would result in 'vv01'. To correct this, the redundant 'v' is removed.
2. In the preservation staging storage, the metadata filename does not have the phrase 'preservation_final_'. Hence 'preservation_final_' is removed.
3. Updated if condition to check if the file or directory specified by metadata_path exist or not.
4. Update the 'dryrun' parameter to 'False' to override the behavior specified by the @dryable(dry_return=('', '', Status.DRY_RUN)) decorator in the job.py file. Previously, the decorator indicated that the code should be executed in dry mode. However, by setting 'dryrun' to False, the code will now execute without the dry mode behavior.
> Fix Issue #36 - Incorrect metadata directory and filename

- README.md
- figshare/Article.py
- requirements.txt
1. This pull request contains code that fixes the bug #33 
2. Updated code to use 'full_name' instead of 'url_name' for first depositor's full name.
3. Handled unicode characters in the full name.
> Fix Issue #33 - Missing first_depositor_full_name in preservation storage folder creation 

- app.py
This pull request contains the code related to the functionality mentioned in issue #22 
Validations have been added for the 'post_processing_script_command' parameter to check if it is empty and log an error if it is. Additionally, it verifies the existence and accessibility of the specified post-processing external script folder, logging an error if it cannot be reached or read.
> Add validations for ‘post-processing script’ parameter in configuration file

- app.py
- bagger/config/__init__.py
- figshare/Integration.py
This pull request must be merged before pull request #45. 
This pull request contains the code that implements the functionality mentioned in issue #43. 
As part of this pull request, two files are modified. Please find below file names
1. 'bagger/config/__init__.py' - Added code to parse command line argument '--Ids'
2. figshare/Integration.py - A new function is added to extract article and collection IDs from command-line argument
1. Information about file: 'bagger/config/__init__.py'
As mentioned above, currently, the parsing of command line argument '--Ids' is done in the 'bagger/config/__init__.py' file.
To see the exact location where it is parsed in the 'bagger/config/init.py' file, please refer to the following link:
https://github.com/UAL-RE/ReBACH/blob/2da807593594458fda13e4c36f …
> Address Issue 43 - Enhance ReBACH to accept specific article and collection IDs for selective processing

- app.py
- figshare/Article.py
- figshare/Collection.py
This pull request must be merged after pull request #44 to avoid errors during code execution. If this order is not followed, an error will be thrown.
Please find below the list of functionalities that have been accomplished through the code added in this pull request.
1. Code to accept specific article and collection IDs from a command-line argument is already achieved as part of enhancement #43 . However, as part of this pull request a code has been added to perform the processing and uploading of those specific article and collection Ids.
Please refer to the commits titled 'Add processing and upload of collections based on IDs' and 'Add processing and upload of articles based on IDs' to see the precise details of the added code and its specific location.
2. Currently, the required …
> Address Issue 27 - Selective processing and uploading of articles and collections mentioned in the command-line argument 

- figshare/Article.py
Makes checks for files in UAL_RDM case insensitive
See #57 
> Feat: Case insensitive filename comparisons (Issue #57)

- bagger/config/default.example.toml
Adds the option `delete` to the bagger config. Set it to True which is the default.
Fixes #69
> Fix: Add missing option to bagger config (Issue #69)

- Log.py
- app.py
- figshare/Article.py
- figshare/Collection.py
Detects whether the console supports ANSI escape sequences and if so, adds color to errors and warnings
Closes #62 
To implement this, it required additional changes to fix the sloppy logging implementation
> Feat: Add color to messages in the console (Issue #62)

- figshare/Article.py
Added extra code to return the result of the operations that caused the execution to continue on error. Previously, no action was taken when there was an error. 
Fixes #60  
*Screenshots or additional context*
Note the fixes for this also partially address Issue #61 
Tested using datasets that exhibited an error during copying files (e.g., 16638328 where one of the curation files permissions were set such that they could not be read by the user that was executing ReBACH)
> Fix: bags uploaded despite error (Issue #60)

- figshare/Article.py
Adds retries to certain uses of requests.get (notably, when downloading the data files of figshare records). 
Fixes #81
Ran the code and under normal circumstances, it works as before. Did not specifically test the error condition since HTTP errors are unpredictable.
> Fix: add retries to file downloading (Issue #81)

- figshare/Article.py
- figshare/Integration.py
Set `process_article` = True on L591 of Article.py. This causes `__final_process` to enter the conditional `if check_files and copy_files:` on L806 due to the fact that `check_files` will now be True. This causes the code to retry downloading the files after failed validation.
Fixes #89
*Screenshots or additional context*
This fix in in the context of Section 4.4 Step 5a in the spec.
Tested on stage with IDs 7844538,7873476
> Fix: incorrect bag is processed (Issue #89)

- bagger/config/default_workflow.json
- profiles/redata-bagit-dart-v2.1.json
- profiles/redata-bagit-v2.1.json
- Internal-sender-identifier is now required
- updated version numbers
- set the bagItProfileIdentifier field to the corresponding URL for standard or DART profiles. This means that for the standard profile, the bagItProfileIdentifier  points to `redata-bagit-vxx.json` and for the DART profile it points to `redata-bagit-dart-vxx.json`
Closes #94 
Tested on 2024-02-06. The Alt ID in APTrust shows the value of internal-sender-identifier (set to the item's DOI). Can use the APTrust API to return only objects with a certain prefix.
> Feat: Improve Bagit profiles for APTrust (Issue #94)

- app.py
- figshare/Article.py
- figshare/Integration.py
Re-worded some existing end-of-run summary messages and added a new counter to track the number of items successfully sent to preservation storage. The computation of some of the counters will need to be updated once the program logic starts excluding already preserved items from processing (refer to PR #93)
See #97 
None
> Feat: Improve summary messages (Issue #97)

- figshare/Article.py
Fixes a few bugs related to the disk size needs computation by being more careful about which folders are counted.
See #96
None
> Feat: Fix free disk space needs computation (Issue #96)

- bagger/config/default.example.toml
- bagger/config/default_workflow.json
- profiles/redata-bagit-dart-v2.2.json
- profiles/redata-bagit-v2.2.json
The Bagger default config now writes the DOI to the Internal-Sender-Identifier field
Fixes #100 
*Screenshots or additional context*
None
Created a bag and uploaded to APTrust. The Internal-Sender-Identifier (the DOI) shows up as the Alt_ID field in APTrust
> Fix: Write Internal-Sender-Identifier to bags (Issue #100)

- README.md
- app.py
- figshare/Article.py
- figshare/Collection.py
Add the dry run functionality by a run time flag `--dry-run`. Setting the flag enables dry run mode where only read operations are executed
Fixes #41 
It has been tested for articles and collections and it behaves as expected
> Feat: describe enhancement or feature (Issue #41)

- bagger/bag.py
`dart-runner` versions greater than 0.96 create an "_artifacts' directory in addition to the .tar file for a bag in the `output_dir`. The "_artifacts" directory contains only the metadata files in .txt format. Compared to `dart-runner 0.96`, the later versions also return a slightly different data structure and keys after successfully processing a bag, thereby creating a `KeyError`. Regardless of the `KeyError`, bags are generated successfully, but bagger reports errors after a run. This PR removes the "_artifacts" folder and fixes the `KeyError`, hence bagger will be able to use `dart-runner 0.96` or greater.
- Remove "_artifacts" directory after creating the .tar file.
- Consider differences in keys and structure returned by different `dart-runner` versions after successfully processing …
> Bug: Remove artifacts directory created by dart-runner v>0.96 in the directory where bags are placed 

- figshare/Article.py
- figshare/Collection.py
This PR corrects a logical error that hinders retrying when an API request fails during the fetching of items in the preprocessing stage.
Fixes #88 
**Testing (if applicable)**
See #88 description.
> Fix: Sometimes API requests fail but retry doesn't work
